#!/bin/sh

[ -n "$BASH_VERSION" -a -f "$HOME/.config/bash.bashrc" ] && . "$HOME/.config/bash.bashrc"

if command -v nvim > /dev/null; then export EDITOR="nvim" MANPAGER="nvim +Man!"
elif command -v vim > /dev/null; then export EDITOR="vim" MANPAGER="vim --not-a-term -M +MANPAGER -"
elif command -v vi > /dev/null; then export EDITOR="vi"
fi

export INPUTRC="$HOME/.config/inputrc"
export LESSHISTFILE="-"
