set nocompatible

runtime! ftplugin/man.vim

set viminfofile=NONE
set lazyredraw
set wildmenu
set number
set relativenumber
set cursorline
set showmatch
set hlsearch
set scrolloff=8
set sidescrolloff=8
set autoindent
set softtabstop=4
set shiftwidth=4
set expandtab
set dictionary=/usr/share/dict/words

if &t_Co >= 256
    set background=dark
    "colorscheme default
    "colorscheme habamax
    "colorscheme custom-default
    colorscheme custom-habamax
endif

autocmd FileType make    setlocal noexpandtab
autocmd FileType sh,bash setlocal foldmethod=syntax
autocmd FileType sh,bash setlocal foldcolumn=1
autocmd FileType sh,bash setlocal colorcolumn=80

let g:sh_fold_enabled=1
"let sh_minlines=500

nnoremap <leader><Up> :resize +2<CR>
nnoremap <leader><Down> :resize -2<CR>
nnoremap <leader><Right> :vertical resize +2<CR>
nnoremap <leader><Left> :vertical resize -2<CR>

function StripTrailingWhitespace()
    if !&binary && &filetype != 'diff'
        normal mz
        %s/\s\+$//e
        normal `z
    endif
endfunction

autocmd BufWrite * :call StripTrailingWhitespace()
